[package]
name = "multiindex_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
slab = "0.4.9"
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"